### ISSUE TITLE
Update to List of Files and Map

### ISSUE THREAD

**Issue by eocathcart** [GreenBuildingRegistry/bpd-gui#102]
From Travis (9/26/23). 
"I just updated the BPD API with some new data.

Could you update the "List of Files" section of the website please? See the attached .csv files. The link text should be the same as the filename except without the trailing ".csv". The contents of all of the files have changed, and the list of file names has changed too.
 
Also, on the "Buildings Per State" map, could you please change New Mexico to the <5k color? All the other states should stay as is."

**Comment by fablet** [comment]
@eocathcart  I don't see that email, so I don't have the files Travis mentioned.  Could you forward that email to me or drop the files in this gissue

**Comment by eocathcart** [comment]
[public-datasets.zip](https://github.com/GreenBuildingRegistry/bpd-gui/files/12731039/public-datasets.zip)

**Comment by eocathcart** [comment]
![BPD US Map 2023](https://github.com/GreenBuildingRegistry/bpd-gui/assets/25183448/1c881022-0aed-4b85-9d25-a747df70a9f1)
