### ISSUE TITLE
Automate Number of Buildings by State map - suggestion

### ISSUE THREAD

**Issue by fablet** [GreenBuildingRegistry/bpd-gui#104]
@eocathcart  This is just a suggestion that I thought might be worth putting out there  to BPD to maybe get some budget for in the next work batch:

I believe it is possible for us to automate the number of buildings by state map using Google's GeoChart. https://developers.google.com/chart/interactive/docs/gallery/geochart

I'd need to touch base with Travis to see where those numbers are coming from, but if I can access them from their API, or they can add an endpoint so that I can, we would be able to keep the map up to date for them automatically.

I believe this would take me less than 8 hours (possibly closer to 4) to integrate this with a working endpoint supplying the numbers

Below is just a reference for me:
```
options = {
      region: 'US',
      displayMode: 'regions',
      resolution: 'provinces',
    };
    ```

**Comment by eocathcart** [comment]
Travis wanted a tweak to the map, so in the short term here is the final static map.

![BPD US Map BlueScale2](https://github.com/GreenBuildingRegistry/bpd-gui/assets/25183448/8070ee16-3b78-431c-851f-bea7bff76bbc)

**Comment by eocathcart** [comment]
Travis gave the go ahead on your idea to build the dynamic map based on the API. Here is his response:

Yes, please automate this. The API already provides the data needed:
- The count in the bottom left is the "number_of_matching_buildings" field from a call to the count endpoint with filters={}.
- The counts for each state in the map are from a call to the histogram endpoint with filters={} and group_by=["state"].

You'll need to mirror the same color palette I'm using the final static map, which is a blue sequential scheme. Let me know if you need the hex for each color region.
